.Dd August 24, 2001
.Dt TTYLOAD 1
.Os
.Sh NAME
.Nm ttyload
.Nd a tty-based xload equivalent
.Sh SYNOPSIS
.Nm ttyload
.Op Fl hvm
.Op Fl c Ar cols
.Op Fl r Ar rows
.Op Fl i Ar seconds
.Sh DESCRIPTION
.Nm
is a
.Dq tty
based load monitoring tool.
Not entirely unlike xload, it plots a graph of a system's
.Dq load average
data.
Unlike xload, it uses 3 line graphs to plot things, instead of a single
fill graph, so that it can show you not only the 1-minute load average,
but also the 5-minute and 15-minute averages.
Also unlike xload, it uses a basic terminal
.Pq tty
to display the information, instead of an X window.
ANSI escape sequences are used
.Pq optionally
for colorization and screen manipulation.
.Pp
A few of the main features of ttyload are:
.Bl -bullet
.It
graphs load averages
.Pq all 3 numbers
over time
.It
uses ANSI escape sequences to colorize graphs
.It
works without requiring X11 libraries, in a Terminal window
.It
automatically determines screen size by default
.El
.Sh USAGE
The easiest way to use ttyload is just to invoke the command, with no
additional options.
.Pp
Additional options are described below.
.Pp
To quit ttyload, enter the terminal's interrupt character
.Pq typically control-C .
.Sh OPTIONS
.Nm
uses standard
.Xr getopt 3
style options processing.
Available options are:
.Bl -tag -width "-i seconds "
.It Fl h
Display a brief usage statement
.Pq Dq help .
.It Fl v
Show version info, then exit.
.It Fl m
Enable monochrome mode
.Pq no ANSI escapes .
.It Fl c Ar cols
Set the number of columns wide to make the display.
If not specified, the default is to determine width automatically.
.It Fl r Ar rows
Set the number of rows high to make the display.
If not specified, the default is to determine height automatically.
.It Fl i Ar seconds
Alter the number of seconds in the interval between refreshes.
The default is 4, and the minimum is 1, which is silently clamped.
.El
.Sh SEE ALSO
.Xr getopt 3
.Sh VERSION
This man page is current for version 0.5 of
.Nm .
.Sh THANKS
Thanks to several my friends for testing things out on various
platforms, or lending me accounts on their machines upon which
to do porting.
.Sh AUTHOR
.Nm
was written by David Lindes.
Please send any feedback, including bug reports and patches, to me.
My contact information
.Pq as well as updates and other information
can be found on the ttyload web page at:
.Lk http://www.daveltd.com/src/util/ttyload/
